default_platform :ios

platform :ios do
  before_all do
    carthage(platform: "iOS")
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    gym(scheme: "Rewatch", use_legacy_build_api: true)
    pilot(skip_submission: true)
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    snapshot
    match(type: "appstore", git_url: "git@github.com:Palleas/match-certificates.git")
    gym(scheme: "Rewatch", configuration: "Release")
    deliver(submit_for_review: false)
  end
end
