default_platform :ios

platform :ios do
  before_all do
    if !File.exist?("Rewatch/Resources/Keys.plist")
      set_info_plist_value(path: "Rewatch/Resources/Keys.plist", key: "BetaseriesAPIKey", value: prompt(text: "Betaseries API Key?"))
      set_info_plist_value(path: "Rewatch/Resources/Keys.plist", key: "BetaseriesAPISecret", value: prompt(text: "Betaseries API Secret?"))
      set_info_plist_value(path: "Rewatch/Resources/Keys.plist", key: "MixpanelAPIKey", value: prompt(text: "Mixpanel API Secret?"))
    end

    if !File.exist?("Rewatch/Resources/Rewatch.xcconfig")

    end

    carthage(platform: "iOS")
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    ensure_git_status_clean
    gym(scheme: "Rewatch", use_legacy_build_api: true)
    pilot(skip_submission: true)
    reset_git_repo(exclude: "Carthage")
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    ensure_git_status_clean
    
    snapshot

    match(type: "appstore", git_url: "git@github.com:Palleas/match-certificates.git")
    gym(scheme: "Rewatch", configuration: "Release")
    deliver(submit_for_review: false)
    
    reset_git_repo(exclude: "Carthage")
  end
end
