default_platform :ios

platform :ios do
  before_all do
    keys_path = File.expand_path File.dirname(__FILE__) + "/../Rewatch/Resources/Keys.plist"
    if !File.exist?(keys_path)
      set_info_plist_value(path: keys_path, key: "BetaseriesAPIKey", value: prompt(text: "Betaseries API Key?"))
      set_info_plist_value(path: keys_path, key: "BetaseriesAPISecret", value: prompt(text: "Betaseries API Secret?"))
      set_info_plist_value(path: keys_path, key: "MixpanelAPIKey", value: prompt(text: "Mixpanel API Secret?"))
    end

    carthage(platform: "iOS")
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    ensure_git_status_clean
    gym(scheme: "Rewatch", use_legacy_build_api: true)
    pilot(skip_submission: true)
    reset_git_repo(exclude: "Carthage")
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    ensure_git_status_clean
    
    snapshot

    match(type: "appstore", git_url: "git@github.com:Palleas/match-certificates.git")
    gym(scheme: "Rewatch", configuration: "Release")
    deliver(submit_for_review: false)
    
    reset_git_repo(exclude: ["Carthage", "Rewatch/Resources/Keys.plist"])
  end
end
