languages([
  "en-US"
])

devices([
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 5",
  "iPhone 4s",
])

launch_arguments("snapshot")
scheme "Rewatch"
output_directory "./screenshots"
clear_previous_screenshots
